name=SN74HC573
version=1.0.6
author=KITTEN2008
maintainer=KITTEN2008
sentence=Library for SN74HC573AN / 74HC573A 8-bit transparent latch.
paragraph=Supports individual bit control, shift operations, LED matrices and 7-segment displays.
category=Signal Input/Output
url=https://github.com/KITTEN2008/74HC573A
architectures=*
depends=
includes=SN74HC573.h
